import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ChatbotWrapper from "./components/ChatbotWrapper";
import FriendMessagingWrapper from "./components/messaging/FriendMessagingWrapper";
import { StoriesProvider } from "./context/StoriesContext";
import { CommentsProvider } from "./context/CommentsContext";
import { MessagingProvider } from "./context/MessagingContext";
import { NotificationProvider } from "./context/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create app",
  viewport: "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <StoriesProvider>
          <CommentsProvider>
            <MessagingProvider>
              <NotificationProvider>
                {children}
                <ChatbotWrapper />
                <FriendMessagingWrapper />
              </NotificationProvider>
            </MessagingProvider>
          </CommentsProvider>
        </StoriesProvider>
      </body>
    </html>
  );
}
